# Generated by Django 3.2.25 on 2025-06-01 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0019_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('adicionado_a', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrinho_itens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-adicionado_a'],
                'unique_together': {('user', 'album')},
            },
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
