# Generated by Django 3.2.25 on 2025-06-05 23:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0020_auto_20250601_2353'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artist',
            new_name='Artista',
        ),
    ]
