# Generated by Django 3.2.25 on 2025-06-06 01:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0021_rename_artist_artista'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artista',
            new_name='Artist',
        ),
    ]
