# Generated by Django 3.2.25 on 2025-06-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_artista_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='spotify_embed_url',
            field=models.URLField(blank=True, help_text='Embed URL from Spotify (e.g. https://open.spotify.com/embed/album/...)', max_length=500),
        ),
    ]
