# Generated by Django 3.2.25 on 2025-06-11 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_album_spotify_embed_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='spotify_embed_url',
        ),
    ]
