# Generated by Django 3.2.25 on 2025-06-13 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_itempedido_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='data_falecimento',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='data_nascimento',
        ),
        migrations.CreateModel(
            name='ArtistaSolo',
            fields=[
                ('artist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.artist')),
                ('data_nascimento', models.DateField()),
                ('data_falecimento', models.DateField(blank=True, null=True)),
            ],
            bases=('core.artist',),
        ),
        migrations.CreateModel(
            name='GrupoMusical',
            fields=[
                ('artist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.artist')),
                ('data_fundacao', models.DateField(blank=True, null=True)),
                ('data_encerramento', models.DateField(blank=True, null=True)),
                ('integrantes', models.ManyToManyField(blank=True, related_name='grupos', to='core.ArtistaSolo')),
            ],
            bases=('core.artist',),
        ),
    ]
