# Generated by Django 3.2.25 on 2025-06-04 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_alter_room_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='owner',
            new_name='dono',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='participants',
            new_name='membros',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='is_private',
            new_name='privado_def',
        ),
    ]
